apiVersion: v1
kind: Namespace
metadata:
  name: gmc-o-prod
  labels:
    name: gmc-o-prod
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gmc-o-quota
  namespace: gmc-o-prod
spec:
  hard:
    requests.nvidia.com/gpu: "100"
    requests.cpu: "500"
    requests.memory: "2Ti"
    persistentvolumeclaims: "120"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: gmc-o-limits
  namespace: gmc-o-prod
spec:
  limits:
  - max:
      nvidia.com/gpu: "1"
      cpu: "8"
      memory: "24Gi"
    min:
      cpu: "1"
      memory: "2Gi"
    type: Container
